alias u='sudo apt update && sudo apt upgrade'
alias la='ls -lah'
alias reboot='systemctl reboot'
alias shutdown='systemctl poweroff'
alias c='clear'
alias logoff='loginctl terminate-user pdawg'
alias grep='grep --color'
alias wtf='curl https://wtfismyip.com/json'
alias n='nvim'
alias b='bat --color=always'
alias gitr='git add . && git commit -a --allow-empty-message -m "" &&  git push'
alias ff='nvim $(fzf)'
alias t='tree -ashC --du'
alias l='ls -lh'
alias h='history'
